---
- name: Extract Forticlient package name
  set_fact:
    forticlient_pkg_remote: "/tmp/{{ forticlient_pkg | basename }}"

- name: Transfer Forticlient package to system
  copy:
    src: "{{ forticlient_pkg }}"
    dest: "{{ forticlient_pkg_remote }}"

- name: Install Forticlient package
  package:
    name: "{{ forticlient_pkg_remote }}"
    state: present
  become: True

- name: Remove the Forticlient package file
  file:
    path: "{{ forticlient_pkg_remote }}"
    state: absent

- name: Install the Fortigate VPN config
  template:
    src: config.j2
    dest: "/etc/openfortivpn/config"
    owner: root
    group: root
    mode: 0600
  become: true

- name: Start the VPN tunnel
  shell: "nohup /bin/openfortivpn --use-syslog &"
  args: 
    chdir: "{{ fortigate_vpn_run_dir }}"
    creates: "/sys/class/net/{{ fortigate_vpn_net_dev }}"
  become: true

- name: Wait for link establishment
  wait_for:
    path: "/sys/class/net/{{ fortigate_vpn_net_dev }}"
    timeout: 60

- name: Enable IP forwarding between interfaces
  sysctl:
    name: "net.ipv4.ip_forward"
    value: 1
  become: true

- name: Enable NAT over the firewall tunnel
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ fortigate_vpn_net_dev }}"
    jump: MASQUERADE
    state: present
  become: true
