---
- name: Create entries in /etc/hosts for all nodes
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}.{{ ansible_domain }} {{ item }}"
    regexp: "^.* {{ item }}$"
    create: no
    state: present
  become: true
  when: "'ansible_default_ipv4' in hostvars[item]"
  with_items:
    - "{{ ansible_play_hosts }}"

