---
# Base configuration for all servers to enable net access
- hosts: cluster
  tasks:
  - name: Enable HTTP access via proxy
    lineinfile:
      path: "/etc/environment"
      create: yes
      mode: 0644
      owner: root
      group: root
      line: "{{ item }}"
    become: True
    with_items:
    - "export http_proxy={{ phe_http_proxy }}"
    - "export https_proxy={{ phe_http_proxy }}"

  roles:
    - role: cluster_hosts
    - role: resmo.ntp
      become: true

# Configure the Fortigate VPN (as best we can)
- hosts: infra_net
  roles:
    - role: fortigate_vpn
      fortigate_pkg: "{{ fortigate_pkg }}"
      fortigate_cfg: "{{ hpcdirect_fortigate }}"

- hosts: infra_user
  pre_tasks:
    - name: Ensure the PHE home directory exists
      file:
        path: "{{ phe_home }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      become: true

    - name: Ensure RDO repo is present
      package:
        name: "centos-release-openstack-pike"
        state: present
      become: true

    - name: Install OpenStack client packages and dependencies
      package:
        name:
          - "python-openstackclient"
          - "python-heatclient"
          - "python-barbicanclient"
          - "python-virtualenv"
        state: present
      become: true

    - name: Extract the infra_net IP
      set_fact:
        gw_ip: "{{ hostvars['infra-net-0']['ansible_default_ipv4']['address'] }}"

    - name: Read routing table
      command: "/usr/sbin/ip route list"
      register: route_table

    - name: Configure routes for VPN
      command: "ip route add {{ item }} via {{ gw_ip }}"
      become: true
      when: route_table.stdout.find(item) == -1
      with_items:
        - "172.27.0.0/16"
        - "10.109.0.0/16"

  roles:
    - role: singleplatform-eng.users
      become: true
      users: "{{ phe_users }}"
      groups_to_create: "{{ phe_groups }}"

    - role: stackhpc.os-config
      os_config_content: "{{ cloud_config }}"
 
  post_tasks:
    - name: Assign cloudadm group access to clouds.yaml
      file:
        path: "/etc/openstack/clouds.yaml"
        owner: "root"
        group: "cloudadm"
        mode: 0640
        state: file
      become: true
